// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:aee95669-149e-4161-a88a-d7819ba4b8c6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FXDEt4McE",
    "aws_user_pools_web_client_id": "1ai0phf20kn7v73cmh47td1efq",
    "oauth": {}
};


export default awsmobile;
